name: Sync Immich Images to Aliyun ACR

on:
  workflow_dispatch:
    inputs:
      immich_version:
        description: 'Immich Target Version Tag'
        required: true
        default: 'v3.1.0'
  push:
    branches:
      - main

env:
  IMMICH_VERSION: ${{ github.event.inputs.immich_version || 'v3.1.0' }}
  REGISTRY: 'registry.cn-shanghai.aliyuncs.com'
  NAMESPACE: 'rocm-forge'

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 使用你配置的账户和密码登录阿里云上海 ACR
      - name: Log in to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

# 4. Valkey (Redis 替代品) 镜像
      - name: Pull, Tag and Push Valkey
        run: |
          docker pull valkey/valkey:8.0-alpine
          docker tag valkey/valkey:8.0-alpine ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/valkey:8.0-alpine
          docker push ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/valkey:8.0-alpine
